// @ts-nocheck
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <p>Name: {data.name}</p>
      </main>
    </>
  )
}

export async function getServerSideProps({ res }) {
  res.setHeader(
    'Cache-Control',
    'kek, s-maxage=10, stale-while-revalidate=59'
  )

  const response = await fetch('https://jsonplaceholder.typicode.com/users/1')

  const { name } = await response.json()

  return {
    props: { data: { name } }, // will be passed to the page component as props
  }
}
